### ISSUE TITLE
Fix >>wiki command not fetching data correctly when there is a disambiguation

### ISSUE THREAD

**Issue by abraker95** [abraker95/apex-sigma#21]

**Comment by abraker95** [comment]
```
Jun 03 22:28:13 minibian run.sh[18219]: Traceback (most recent call last):
Jun 03 22:28:13 minibian run.sh[18219]: File "/home/server/discord/sigma/sigma/core/callable.py", line 92, in call
Jun 03 22:28:13 minibian run.sh[18219]: msg = await getattr(self.module, self.name)(self, message, *args)
Jun 03 22:28:13 minibian run.sh[18219]: File "/home/server/discord/sigma/sigma/plugins/searches/wikipedia/wiki.py", line 7, in wiki
Jun 03 22:28:13 minibian run.sh[18219]: result = wikipedia.summary(q)
Jun 03 22:28:13 minibian run.sh[18219]: File "/usr/local/lib/python3.6/site-packages/wikipedia/util.py", line 28, in __call__
Jun 03 22:28:13 minibian run.sh[18219]: ret = self._cache[key] = self.fn(*args, **kwargs)
Jun 03 22:28:13 minibian run.sh[18219]: File "/usr/local/lib/python3.6/site-packages/wikipedia/wikipedia.py", line 231, in summary
Jun 03 22:28:13 minibian run.sh[18219]: page_info = page(title, auto_suggest=auto_suggest, redirect=redirect)
Jun 03 22:28:13 minibian run.sh[18219]: File "/usr/local/lib/python3.6/site-packages/wikipedia/wikipedia.py", line 276, in page
Jun 03 22:28:13 minibian run.sh[18219]: return WikipediaPage(title, redirect=redirect, preload=preload)
Jun 03 22:28:13 minibian run.sh[18219]: File "/usr/local/lib/python3.6/site-packages/wikipedia/wikipedia.py", line 299, in __init__
Jun 03 22:28:13 minibian run.sh[18219]: self.__load(redirect=redirect, preload=preload)
Jun 03 22:28:13 minibian run.sh[18219]: File "/usr/local/lib/python3.6/site-packages/wikipedia/wikipedia.py", line 393, in __load
Jun 03 22:28:13 minibian run.sh[18219]: raise DisambiguationError(getattr(self, 'title', page['title']), may_refer_to)
Jun 03 22:28:13 minibian run.sh[18219]: wikipedia.exceptions.DisambiguationError: "Test" may refer to:
<omitted>
```
